//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SobujBanglaARM
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_tblDistrict
    {
        public int Id { get; set; }
        public int DivId { get; set; }
        public string Name { get; set; }
        public string NameBangla { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
        public string URL { get; set; }
    }
}
