//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SobujBanglaARM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SobujBanglaARMEntities : DbContext
    {
        public SobujBanglaARMEntities()
            : base("name=SobujBanglaARMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBank> tblBanks { get; set; }
        public virtual DbSet<tblBankTransaction> tblBankTransactions { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblCostCenter> tblCostCenters { get; set; }
        public virtual DbSet<tblCostElement> tblCostElements { get; set; }
        public virtual DbSet<tblEmail> tblEmails { get; set; }
        public virtual DbSet<tblExpense> tblExpenses { get; set; }
        public virtual DbSet<tblIncome> tblIncomes { get; set; }
        public virtual DbSet<tblIncomeSource> tblIncomeSources { get; set; }
        public virtual DbSet<tblItemSize> tblItemSizes { get; set; }
        public virtual DbSet<tblItemType> tblItemTypes { get; set; }
        public virtual DbSet<tblLogIn> tblLogIns { get; set; }
        public virtual DbSet<tblPacking> tblPackings { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
        public virtual DbSet<tblPurchaseDTL> tblPurchaseDTLs { get; set; }
        public virtual DbSet<tblPurchaseHDR> tblPurchaseHDRs { get; set; }
        public virtual DbSet<tblRecipient> tblRecipients { get; set; }
        public virtual DbSet<tblSalesDTL> tblSalesDTLs { get; set; }
        public virtual DbSet<tblSalesHDR> tblSalesHDRs { get; set; }
        public virtual DbSet<tblSalesReturn> tblSalesReturns { get; set; }
        public virtual DbSet<tblStock> tblStocks { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblMoneyReceived> tblMoneyReceiveds { get; set; }
        public virtual DbSet<tblStockDetail> tblStockDetails { get; set; }
        public virtual DbSet<View_Customers> View_Customers { get; set; }
        public virtual DbSet<M_tblDistrict> M_tblDistrict { get; set; }
        public virtual DbSet<M_tblUpazila> M_tblUpazila { get; set; }
        public virtual DbSet<M_tblVillage> M_tblVillage { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblSupplier> tblSuppliers { get; set; }
        public virtual DbSet<tblCompany> tblCompanies { get; set; }
        public virtual DbSet<tblItem> tblItems { get; set; }
    }
}
