//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SobujBanglaARM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExpense
    {
        public int Id { get; set; }
        public Nullable<int> CostHead { get; set; }
        public Nullable<int> CostElement { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> StaffId { get; set; }
        public string HandedTo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remarks { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> Lmdt { get; set; }
        public Nullable<int> IdClient { get; set; }
    }
}
