//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SobujBanglaARM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmail
    {
        public int MODULEID { get; set; }
        public int UIID { get; set; }
        public string RPTCATEGORY { get; set; }
        public string USERNAME { get; set; }
        public string FROMEMAILID { get; set; }
        public string SUBJECT { get; set; }
        public string BODY { get; set; }
        public string LMBY { get; set; }
        public Nullable<System.DateTime> LMDT { get; set; }
        public string IPADDRESS { get; set; }
        public string MACHINEID { get; set; }
        public string FILEPATH { get; set; }
        public string EMAILPWD { get; set; }
        public string SMTPHOST { get; set; }
        public Nullable<int> PORT { get; set; }
        public Nullable<bool> SSLSTATUS { get; set; }
    }
}
