//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SobujBanglaARM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseDTL
    {
        public int PurId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> Lmdt { get; set; }
        public Nullable<int> IdClient { get; set; }
    }
}
