//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SobujBanglaARM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesDTL
    {
        public string SalesId { get; set; }
        public Nullable<int> CustId { get; set; }
        public string Itemcode { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> Lmdt { get; set; }
        public Nullable<int> IdClient { get; set; }
        public string Source { get; set; }
    }
}
