//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SobujBanglaARM
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Customers
    {
        public int CustId { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Religion { get; set; }
        public Nullable<int> OccupId { get; set; }
        public string Reference { get; set; }
        public Nullable<int> DistId { get; set; }
        public Nullable<int> ThanaId { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<int> ViId { get; set; }
        public string Address { get; set; }
        public string Remarks { get; set; }
        public byte[] Photo { get; set; }
        public string IsSupplier { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> Lmdt { get; set; }
        public string OccupationName { get; set; }
        public string DistrictName { get; set; }
        public string ThanaName { get; set; }
        public string PostName { get; set; }
        public string VillageName { get; set; }
    }
}
